version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env

  app:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    tty: true
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db

volumes:
  data-volume: